name: Update Formula

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  update-formula:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Get latest release tag
        id: latest_tag
        run: echo "::set-output name=tag::$(curl -s https://api.github.com/repos/raspberrypi/usbboot/releases/latest | jq -r .tag_name)"

      - name: Get SHA256 checksum
        id: shasum
        run: echo "::set-output name=sha::$(curl -L https://github.com/raspberrypi/usbboot/archive/refs/tags/${{ steps.latest_tag.outputs.tag }}.tar.gz | sha256sum | awk '{ print $1 }')"

      - name: Update rpiboot homebrew formula
        uses: naijabx/update-formula-homebrew-action@v1.1
        with:
          repo: PanterSoft/homebrew-pantersoft
          tap: PanterSoft/homebrew-pantersoft
          formula: Formula/rpiboot.rb
          download-url: https://github.com/raspberrypi/usbboot/archive/refs/tags/${{ steps.latest_tag.outputs.tag }}.tar.gz
          sha256: ${{ steps.shasum.outputs.sha }}
        env:
          COMMIT_TOKEN: ${{ secrets.BREW_TOKEN_TAP }}