name: Update rpiboot Formula

on:
  push:
    branches:
      - main
  schedule:
    - cron: '0 0 * * 0'  # Run every Sunday at midnight

jobs:
  update-formula:
    runs-on: ubuntu-20.04

    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Get latest release tag
        id: latest_tag
        run: |
          LATEST_RELEASE=$(curl -s https://api.github.com/repos/raspberrypi/usbboot/releases/latest | jq -r .tag_name)
          if [ -z "$LATEST_RELEASE" ]; then
            echo "No releases found"
            exit 1
          fi
          echo "::set-output name=tag::$LATEST_RELEASE"

      - name: Get SHA256 checksum
        id: shasum
        run: |
          wget https://github.com/raspberrypi/usbboot/archive/refs/tags/${{ steps.latest_tag.outputs.tag }}.tar.gz
          echo ::set-output name=sha::"$(sha256sum ./${{ steps.latest_tag.outputs.tag }}.tar.gz | awk '{print $1}')"

      - name: Verify Homebrew Token
        run: |
          if [ -z "${{ secrets.BREW_TOKEN_TAP }}" ]; then
            echo "BREW_TOKEN_TAP is not set"
            exit 1
          fi

      - name: Update rpiboot homebrew formula
        uses: naijabx/update-formula-homebrew-action@v1.1
        with:
          repo: raspberrypi/usbboot
          tap: PanterSoft/homebrew-pantersoft
          formula: Formula/rpiboot.rb
          download-url: https://github.com/raspberrypi/usbboot/archive/refs/tags/${{ steps.latest_tag.outputs.tag }}.tar.gz
          sha256: ${{ steps.shasum.outputs.sha }}
          commit-message: update rpiboot formula
        env:
          COMMIT_TOKEN: ${{ secrets.BREW_TOKEN_TAP }}